# Generated by Django 5.2.8 on 2026-07-01 19:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMexico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaDirectorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('domicilio', models.CharField(blank=True, max_length=255, verbose_name='Domicilio')),
                ('ciudad', models.CharField(blank=True, max_length=120, verbose_name='Ciudad')),
                ('firma_encargado', models.CharField(max_length=150, verbose_name='Firma del Encargado')),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Usa dígitos y, opcionalmente, + ( ) - y espacios.', regex='^[0-9+()\\s\\-]{7,20}$')], verbose_name='Teléfono')),
                ('tentativa_resolucion', models.CharField(choices=[('INTERNACION', 'Internación'), ('RECHAZO', 'Rechazo')], max_length=12, verbose_name='Tentativa de Resolución')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_directorio', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='directorio.estadomexico', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Empresa (Directorio)',
                'verbose_name_plural': 'Directorio de Empresas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['empresa'], name='directorio__empresa_bffe2f_idx'), models.Index(fields=['empresa', 'tentativa_resolucion'], name='directorio__empresa_9d9dd9_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'firma_encargado', 'telefono'), name='uniq_empresa_encargado_tel')],
            },
        ),
    ]
