# Generated by Django 5.2.8 on 2026-07-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_seed_estados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresadirectorio',
            name='tentativa_resolucion',
            field=models.CharField(blank=True, choices=[('INTERNACION', 'Internación'), ('RECHAZO', 'Rechazo')], help_text='Opcional. Puede definirse más adelante.', max_length=12, verbose_name='Tentativa de Resolución'),
        ),
    ]
