# Generated by Django 5.2.8 on 2025-11-19 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='uploads/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Carga',
                'verbose_name_plural': 'Lotes de Carga',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuelo_numero', models.CharField(max_length=50, verbose_name='航班号')),
                ('vuelo_fecha', models.DateTimeField(blank=True, null=True, verbose_name='航班日期')),
                ('aeropuerto_salida', models.CharField(max_length=50, verbose_name='起飞机场')),
                ('aeropuerto_llegada', models.CharField(max_length=50, verbose_name='落地机场')),
                ('salida_planificada', models.CharField(blank=True, max_length=50, null=True, verbose_name='计划离港')),
                ('nombre_pasajero', models.CharField(max_length=200, verbose_name='旅客姓名')),
                ('numero_documento', models.CharField(max_length=100, verbose_name='证件号')),
                ('numero_asiento', models.CharField(max_length=20, verbose_name='座位号')),
                ('numero_equipaje', models.TextField(blank=True, null=True, verbose_name='行李号')),
                ('piezas', models.IntegerField(default=0, verbose_name='件数')),
                ('peso', models.IntegerField(default=0, verbose_name='重量')),
                ('estado_checkin', models.CharField(max_length=50, verbose_name='值机状态')),
                ('informacion_contacto', models.TextField(blank=True, null=True, verbose_name='联系信息')),
                ('contacto_reserva', models.CharField(blank=True, max_length=100, null=True, verbose_name='预订人联系方式')),
                ('contacto_pasajero', models.CharField(blank=True, max_length=100, null=True, verbose_name='乘机人联系方式')),
                ('numero_ticket', models.CharField(max_length=100, verbose_name='票号')),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=20, null=True, verbose_name='旅客生日')),
                ('genero', models.CharField(max_length=10, verbose_name='性别')),
                ('codigo_pais_emision', models.CharField(max_length=10, verbose_name='签发国编码')),
                ('pais_emision', models.CharField(max_length=100, verbose_name='签发国')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('inadmitido', models.BooleanField(default=False, verbose_name='Inadmitido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='uploader.uploadbatch')),
            ],
            options={
                'verbose_name': 'Registro de Pasajero',
                'verbose_name_plural': 'Registros de Pasajeros',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
