# Generated by Django 5.2.8 on 2025-11-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='旅客生日'),
        ),
    ]
