# Generated by Django 5.2.8 on 2025-12-01 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_alter_registro_contacto_pasajero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('importante', 'Importante'), ('no_importante', 'No Importante')], default='no_importante', max_length=20, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('duplicados', 'Duplicados Detectados'), ('casos_especiales', 'Casos Especiales'), ('error_registro', 'Error en Registro'), ('carga_exitosa', 'Carga Exitosa'), ('sistema', 'Sistema')], max_length=30, verbose_name='Categoría')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enlace', models.CharField(blank=True, help_text='URL a la que redirige la notificación', max_length=500, null=True, verbose_name='Enlace')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='uploader_no_usuario_bbdfca_idx'), models.Index(fields=['tipo'], name='uploader_no_tipo_cfafe4_idx'), models.Index(fields=['categoria'], name='uploader_no_categor_386a30_idx'), models.Index(fields=['fecha_creacion'], name='uploader_no_fecha_c_3479b1_idx')],
            },
        ),
    ]
