# Generated by Django 5.2.8 on 2025-11-26 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_registro_fecha_nacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.CharField(choices=[('documento_duplicado', 'Número de Documento Duplicado'), ('mismo_vuelo_fecha', 'Mismo Vuelo y Fecha'), ('datos_sospechosos', 'Datos Sospechosos')], default='documento_duplicado', max_length=50, verbose_name='Razón')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aceptado', 'Aceptado por Admin'), ('editado', 'Documento Editado'), ('inadmitido', 'Marcado como Inadmitido'), ('eliminado', 'Eliminado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('registros_conflictivos_ids', models.JSONField(default=list, help_text='Lista de IDs de registros con el mismo documento', verbose_name='IDs de Registros Conflictivos')),
                ('documento_original', models.CharField(help_text='Número de documento que causó el conflicto', max_length=100, verbose_name='Documento Original')),
                ('documento_nuevo', models.CharField(blank=True, help_text='Nuevo número de documento si fue editado', max_length=100, null=True, verbose_name='Documento Nuevo')),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Notas del Administrador')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caso_especial', to='uploader.registro', verbose_name='Registro')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto Por')),
            ],
            options={
                'verbose_name': 'Caso Especial',
                'verbose_name_plural': 'Casos Especiales',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='uploader_ca_estado_078340_idx'), models.Index(fields=['documento_original'], name='uploader_ca_documen_5c275f_idx'), models.Index(fields=['fecha_creacion'], name='uploader_ca_fecha_c_3b35f7_idx')],
            },
        ),
    ]
