# Generated by Django 5.2.8 on 2025-11-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_casoespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='punto_internacion',
            field=models.BooleanField(default=False, verbose_name='Punto de Internación (PI)'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Segunda Revisión (SR)'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='inadmitido',
            field=models.BooleanField(default=False, verbose_name='Rechazo (R)'),
        ),
    ]
