# Generated by Django 5.2.8 on 2025-11-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_registro_punto_internacion_alter_registro_confirmado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='punto_internacion',
            new_name='internacion',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='inadmitido',
            new_name='rechazado',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='confirmado',
            new_name='segunda_revision',
        ),
    ]
