# Generated by Django 5.2.8 on 2025-12-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_rename_punto_internacion_registro_internacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='contacto_pasajero',
            field=models.TextField(blank=True, null=True, verbose_name='乘机人联系方式'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='contacto_reserva',
            field=models.TextField(blank=True, null=True, verbose_name='预订人联系方式'),
        ),
    ]
