# Generated by Django 5.2.8 on 2025-12-01 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='fecha_vuelo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Vuelo'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='tipo_vuelo',
            field=models.CharField(blank=True, choices=[('PEK-TIJ', 'Pekín - Tijuana'), ('PEK-MEX', 'Pekín - México')], max_length=10, null=True, verbose_name='Tipo de Vuelo'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='vuelo_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Vuelo'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['fecha_vuelo', 'tipo_vuelo'], name='uploader_up_fecha_v_087e5d_idx'),
        ),
    ]
