# Generated by Django 5.2.8 on 2026-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_uploadbatch_fecha_vuelo_uploadbatch_tipo_vuelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoespecial',
            name='razon',
            field=models.CharField(choices=[('documento_duplicado', 'Número de Documento Duplicado'), ('mismo_vuelo_fecha', 'Mismo Vuelo y Fecha'), ('datos_sospechosos', 'Datos Sospechosos'), ('sin_documento', 'Sin Número de Documento')], default='documento_duplicado', max_length=50, verbose_name='Razón'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='证件号'),
        ),
    ]
