# Generated by Django 5.2.8 on 2026-05-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_numero_documento_nullable_sin_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='es_menor',
            field=models.BooleanField(default=False, verbose_name='Es Menor de Edad'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
