# Generated by Django 5.2.8 on 2025-12-08 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0008_uploadbatch_fecha_vuelo_uploadbatch_tipo_vuelo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoRechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Foto del documento o pasajero rechazado', upload_to='rechazos/%Y/%m/%d/')),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la foto', null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_rechazo', to='uploader.registro')),
                ('usuario_captura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que subió la foto')),
            ],
            options={
                'verbose_name': 'Foto de Rechazo',
                'verbose_name_plural': 'Fotos de Rechazos',
                'ordering': ['-fecha_captura'],
                'indexes': [models.Index(fields=['registro', '-fecha_captura'], name='camara_foto_registr_dae239_idx')],
            },
        ),
    ]
