# Generated by Django 5.2.8 on 2026-07-01 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Redaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resolucion', models.CharField(choices=[('INTERNACION', 'Internación'), ('RECHAZO', 'Rechazo')], max_length=12, verbose_name='Resolución')),
                ('tema', models.CharField(max_length=160, verbose_name='Tema')),
                ('archivo', models.FileField(upload_to='redacciones/%Y/%m/', verbose_name='Documento')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='redacciones/pdf/%Y/%m/', verbose_name='PDF para vista previa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redacciones', to='redacciones.pais', verbose_name='País')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redacción',
                'verbose_name_plural': 'Redacciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['resolucion', 'pais'], name='redacciones_resoluc_74dbc3_idx'), models.Index(fields=['tema'], name='redacciones_tema_f602ff_idx')],
            },
        ),
    ]
