# Generated by Django 5.2.8 on 2026-07-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacciones', '0002_seed_paises'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaccion',
            name='texto_contenido',
            field=models.TextField(blank=True, default='', editable=False, help_text='Texto plano extraído del PDF para el buscador de palabras.', verbose_name='Texto extraído del documento'),
        ),
    ]
