# Generated by Django 5.2.8 on 2026-08-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacciones', '0004_redaccion_tipo_contenido_texto_crudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redaccion',
            name='texto_crudo',
            field=models.TextField(blank=True, help_text='Contenido de la redacción pegado directamente (sin archivo).', verbose_name='Texto pegado'),
        ),
    ]
